experiment:
	defaults: &defaults
		root:	/Users/alex/Dropbox/nlp_project
		data:	/Users/alex/Dropbox/nlp_project/data
		working:/Users/alex/Dropbox/nlp_project/working
		output:	/Users/alex/Dropbox/nlp_project/output
	data:
		udp:
			sub_data: /input/raw/universal-dependencies-1.0/en	# in the data folder
			training_file: en-ud-train.conllu
			cross_validation_file: en-ud-dev.conllu
			testing_file: en-ud-test.conllu
			output_file: pos_tags.txt
			gold_output: pos_tags_gold.txt
			iterations: 2
			regularization: [0.1, 0.2, 0.3, 0.5, 0.8, 1.3] # Fibonacci numbers!
		udp-tiny:
			sub_data: /input/raw/universal-dependencies-1.0/en	# in the data folder
			training_file: udp-tiny-train.conllu
			cross_validation_file: en-ud-dev.conllu
			testing_file: udp-tiny-test.conllu
			output_file: pos_tags.txt
			gold_output: pos_tags_gold.txt
			iterations: 1
			regularization: [0.5]